# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HttpDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HttpDemo
  pod 'AFNetworking', '~> 3.1.0'
end
